### ISSUE TITLE
No windows support

### ISSUE THREAD

**Issue by SjoerdNijboer** [SjoerdNijboer/box#5]
We're not supporting windows.
Probably because no one is putting boxes in windows because they might fall out.
I will bring this up during the next design meeting.

**Comment by SjoerdNijboer** [comment]
I just realized we don't have a design meeting planned

**Comment by SjoerdNijboer** [comment]
I'm all out of ideas now.

**Comment by Butt4cak3** [comment]
It's not a bug. It's a conscious decision. Nobody uses Windows anyway.

**Comment by SjoerdNijboer** [comment]
Fair deal.
Windows support is out of scope for now.

**Comment by SjoerdNijboer** [comment]
Out of scope.
Won't do.
